# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"

early_access: false

reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  auto_title_placeholder: "@coderabbitai"
  review_status: true
  collapse_walkthrough: false
  poem: false
  
  path_instructions:
    - path: "**/*.swift"
      instructions: |
        Review Swift code for:
        - SwiftUI best practices and proper use of property wrappers (@State, @Binding, @StateObject, @ObservedObject, @EnvironmentObject)
        - Memory management and potential retain cycles in closures
        - Proper use of async/await and structured concurrency
        - MVVM architecture adherence
        - Accessibility support (VoiceOver, Dynamic Type)
        - Localization readiness
    
    - path: "**/*Tests.swift"
      instructions: |
        Review test files for:
        - Adequate test coverage
        - Proper use of XCTest assertions
        - Mock objects and dependency injection
        - Async testing patterns
    
    - path: "**/Info.plist"
      instructions: |
        Check for:
        - Required privacy usage descriptions
        - Proper bundle identifiers
        - Required device capabilities
    
    - path: "**/*.xcconfig"
      instructions: |
        Verify build configuration settings are appropriate for each environment.

  path_filters:
    - "!**/*.generated.swift"
    - "!**/Pods/**"
    - "!**/.build/**"
    - "!**/DerivedData/**"
    - "!**/*.xcodeproj/**"
    - "!**/*.xcworkspace/**"
    - "!**/Package.resolved"

  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
      - develop

chat:
  auto_reply: true

knowledge_base:
  opt_out: false
  learnings:
    scope: "auto"
  issues:
    scope: "auto"
  pull_requests:
    scope: "auto"