#!/bin/bash

# Script to add test target to SlothyTerminal Xcode project
# This script provides instructions since modifying pbxproj directly is risky

echo "=========================================="
echo "Adding Test Target to SlothyTerminal"
echo "=========================================="
echo ""
echo "The test files have been created in SlothyTerminalTests/"
echo ""
echo "To add the test target in Xcode:"
echo ""
echo "1. Open SlothyTerminal.xcodeproj in Xcode"
echo ""
echo "2. Go to File > New > Target..."
echo ""
echo "3. Select 'macOS' > 'Unit Testing Bundle' and click Next"
echo ""
echo "4. Configure the target:"
echo "   - Product Name: SlothyTerminalTests"
echo "   - Team: (your team)"
echo "   - Bundle Identifier: com.slothyterminal.tests"
echo "   - Language: Swift"
echo "   - Target to be Tested: SlothyTerminal"
echo ""
echo "5. Click Finish"
echo ""
echo "6. Delete the auto-generated test file (SlothyTerminalTests.swift)"
echo ""
echo "7. In the Project Navigator, right-click 'SlothyTerminalTests' folder"
echo "   and select 'Add Files to SlothyTerminalTests...'"
echo ""
echo "8. Navigate to the SlothyTerminalTests folder and add all .swift files:"
echo "   - StatsParserTests.swift"
echo "   - UsageStatsTests.swift"
echo "   - RecentFoldersManagerTests.swift"
echo "   - AgentFactoryTests.swift"
echo ""
echo "9. Make sure 'SlothyTerminalTests' target is selected in the dialog"
echo ""
echo "10. Run tests with Cmd+U or Product > Test"
echo ""
echo "=========================================="
echo "Test Files Location:"
echo "$(ls -la ../SlothyTerminalTests/*.swift 2>/dev/null || echo 'No test files found')"
echo "=========================================="
